title: Renaud's personal website
description: le site personnel de Renaud
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
